### ISSUE TITLE
WOW THIS IS AMAZING!

### ISSUE THREAD

**Issue by McFarts** [fermads/amnesia#1]
Been looking at all these damn options of sharing memory between processes..

Like Redis / Memcache.. all are good but their API BLOWS! You have to literally create and edit your whole app just for it to work together. I'm using a child process for a specific game loop in my game for handling monster positioning and player synchronization and this way is much much easier and faster. Hell, I could even send data off to another server lol.

Question tho:

How is the performance? I'm only doing it this locally and utilizing the cores on my local machine no extra server. I manipulate a LOT of buffer data in my game (player moves an item in their inventory or moving around the map upon each click it gets updated to the buffer) but now, it will be through amensia... any benchmarks tho?

Thx so much to the authors!

**Comment by McFarts** [comment]
Also, will it work under Debian / Linux distro as well?

**Comment by fermads** [comment]
Hello,

It should work as fast as possible considering Node.js performance
standards because it is bare bones TCP connection (core net module). No
other libs/dependencies, no middleware. Also the entire lib is 200 lines of
code. You can easily change it if needed.
Yes, it should work on Debin.

Best Regards
fermads

**Comment by McFarts** [comment]
@fermads  Thank you,

Couple questions:

Since the max size of a TCP packet is around 64k, are u saying I can only share around 64k of data? How about large objects that are like over 1mb of size and need to be updated?

2) Take a look here:

http://stackoverflow.com/questions/32400108/using-tcp-for-memory-sharing-across-processes

**Comment by fermads** [comment]
You should not have any problems with size. Node will buffer/queue your
data if it's too big and send them when the OS gives it a writable socket's
file descriptor.
You may hit performance issues only if you are writing more then you
network bandwidth per second. At this point you'll also use more ram to
queue/buffer all the messages.

fermads
